config/routes.rb
Rails.application.routes.draw do
  resources :channels do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
    has_many :messages
    broadcasts_to ->(channel) { 
        :channels 
    }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  broadcasts_to :channel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1 or /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to channels_url, notice: "Channel was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:title, :about)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_channel, only: [:new, :create]

    def new
      @message = @channel.messages.new
    end

    def create
      @message = @channel.messages.create!(message_params)

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @channel }
      end
    end

    private
      def set_channel
        @channel = Channel.find(params[:channel_id])
      end

      def message_params
        params.require(:message).permit(:content)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<h4 id="<%= dom_id channel %>">
    <%= link_to "##{channel.title}", channel, "data-turbo-frame": "channel" %>
</h4>

app/views/channels/_form.html.erb
<%= form_with(model: channel) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<%= turbo_stream_from :channels %>

<div class="row">
  <div class="col-2">
    <%= link_to 'New Channel', new_channel_path, "data-turbo-frame": "channel" %>
    <%= turbo_frame_tag "channels" do %>
      <%= render @channels %>
    <% end %>
  </div>

  <div class="col-10">
    <%= turbo_frame_tag "channel" do %>
    <% end %>
  </div>
</div>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= turbo_frame_tag "channel" do %>
    <%= render 'form', channel: @channel %>
<% end %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<%= turbo_frame_tag "channel" do %>
<p id="notice"><%= notice %></p>

<%= turbo_stream_from @channel %>

<p>
  <strong>Title:</strong>
  <%= @channel.title %>
</p>

<p>
  <strong>About:</strong>
  <%= @channel.about %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>

<div id="messages">
  <%= render @channel.messages %>
</div>

<%= turbo_frame_tag "new_message", src: new_channel_message_path(@channel), target: "_top" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hotwire Text</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireText</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stimulus_include_tags %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= yield :head %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p id="<%= dom_id message %>">
  <%= message.created_at.to_s(:short) %>: <%= message.content %>
</p>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= turbo_frame_tag "new_message", target: "_top" do %>
    <%= form_with(model: [ @message.channel, @message ]) do |form| %>
        <div class="field">
            <%= form.text_field :content %>
            <%= form.submit "Send" %>
        </div>
    <% end %>
<% end %>

<%= link_to 'Back', @message.channel %>